### ISSUE TITLE
poac.dev packages are down

### ISSUE THREAD

**Issue by oraqlle** [poac-dev/poac.dev#849]
Currently, the poac.dev site does not correctly load the packages page nor can the `poac` tool download dependencies. On the website I get the following error.

```sh
504: GATEWAY_TIMEOUT
Code: FUNCTION_INVOCATION_TIMEOUT
```

It also states the application is up and working and that my own connection is good but a serverless function timed out.

**Comment by ken-matsui** [comment]
@oraqlle Hi, thank you for bringing this to my attention. I apologize for the inconvenience caused. The issue is being caused by the usage of Render's free plan for the API, which appears to have limited resources currently. To resolve this, I am considering moving the basic APIs to Vercel's [Serverless Functions](https://vercel.com/docs/concepts/functions/serverless-functions/runtimes), which also (unofficially) supports [Rust](https://github.com/vercel-community/rust). I will try to complete this task as soon as possible during my free time. Again, apologies for any inconvenience caused.

**Comment by oraqlle** [comment]
No worries @ken-matsui. I'll watch this thread for updates.

**Comment by ken-matsui** [comment]
@oraqlle The issue has been resolved and users should now be able to use poac.dev.
